# Generated by Django 2.2.23 on 2021-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210511_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='increase',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
